#!/bin/bash

declare DOTFILES_DIR_PATH="$(dirname $(dirname $(readlink $BASH_SOURCE)))"

source "$DOTFILES_DIR_PATH/os/utils.sh" \
    && declare OS="$(get_os)"

# ----------------------------------------------------------------------

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias q="exit"
alias rm="rm -rf"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# create static server in the folder this is run to

alias serve="python -m SimpleHTTPServer"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# Tomcat specific
alias tstart="/Library/Tomcat/bin/startup.sh"
alias tstop="/Library/Tomcat/bin/shutdown.sh"


# tail bosweb log files
alias tailBWapp="tail -F /private/var/log/bosweb/Blackwells-websiteinstance_IS_UNDEFINED.log"
alias tailBWinstance="tail -F /private/var/log/bosweb/Blackwells-systeminstance_IS_UNDEFINED.log"
alias tailBobcat="tail -F /private/var/log/bosweb/bos-bobcat-application.log"

# Sauce Lab Shortcuts for running localhost testing
alias bt="sc -u yann-le-corre -k 32f1dfa7-6308-4db1-9e83-c95b4033c490"



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# Load OS specific aliases

if [ "$OS" == "osx" ]; then
    source "$DOTFILES_DIR_PATH/shell/os_x/bash_aliases"
elif [ "$OS" == "ubuntu" ]; then
    source "$DOTFILES_DIR_PATH/shell/ubuntu/bash_aliases"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
unset OS
